/** demonym สัญชาติ (จาก Ergast) → ธงชาติ emoji */
export const NATION_FLAG: Record<string, string> = {
  British: "🇬🇧",
  English: "🇬🇧",
  Dutch: "🇳🇱",
  German: "🇩🇪",
  Spanish: "🇪🇸",
  French: "🇫🇷",
  Italian: "🇮🇹",
  Mexican: "🇲🇽",
  Australian: "🇦🇺",
  Finnish: "🇫🇮",
  Canadian: "🇨🇦",
  Monegasque: "🇲🇨",
  Thai: "🇹🇭",
  Japanese: "🇯🇵",
  American: "🇺🇸",
  Danish: "🇩🇰",
  Chinese: "🇨🇳",
  "New Zealander": "🇳🇿",
  Argentine: "🇦🇷",
  Argentinian: "🇦🇷",
  Brazilian: "🇧🇷",
  Austrian: "🇦🇹",
  Belgian: "🇧🇪",
  Swiss: "🇨🇭",
  Swedish: "🇸🇪",
  Polish: "🇵🇱",
  Russian: "🇷🇺",
  Estonian: "🇪🇪",
  Irish: "🇮🇪",
  "South African": "🇿🇦",
};

export const flag = (nationality?: string) => NATION_FLAG[nationality ?? ""] ?? "🏁";

/** ประเทศของสนาม (Location.country จาก Ergast) → ธงชาติ emoji */
export const COUNTRY_FLAG: Record<string, string> = {
  Australia: "🇦🇺",
  Austria: "🇦🇹",
  Azerbaijan: "🇦🇿",
  Bahrain: "🇧🇭",
  Belgium: "🇧🇪",
  Brazil: "🇧🇷",
  Canada: "🇨🇦",
  China: "🇨🇳",
  France: "🇫🇷",
  Germany: "🇩🇪",
  Hungary: "🇭🇺",
  Italy: "🇮🇹",
  Japan: "🇯🇵",
  Malaysia: "🇲🇾",
  Mexico: "🇲🇽",
  Monaco: "🇲🇨",
  Netherlands: "🇳🇱",
  Portugal: "🇵🇹",
  Qatar: "🇶🇦",
  Russia: "🇷🇺",
  "Saudi Arabia": "🇸🇦",
  Singapore: "🇸🇬",
  "South Africa": "🇿🇦",
  Spain: "🇪🇸",
  Thailand: "🇹🇭",
  Turkey: "🇹🇷",
  UAE: "🇦🇪",
  "United Arab Emirates": "🇦🇪",
  UK: "🇬🇧",
  "United Kingdom": "🇬🇧",
  USA: "🇺🇸",
  "United States": "🇺🇸",
  Vietnam: "🇻🇳",
};

export const countryFlag = (country?: string) => COUNTRY_FLAG[country ?? ""] ?? "🏁";
