/** demonym สัญชาติ (จาก Ergast) → ธงชาติ emoji */
export const NATION_FLAG: Record<string, string> = {
  British: "🇬🇧",
  English: "🇬🇧",
  Dutch: "🇳🇱",
  German: "🇩🇪",
  Spanish: "🇪🇸",
  French: "🇫🇷",
  Italian: "🇮🇹",
  Mexican: "🇲🇽",
  Australian: "🇦🇺",
  Finnish: "🇫🇮",
  Canadian: "🇨🇦",
  Monegasque: "🇲🇨",
  Thai: "🇹🇭",
  Japanese: "🇯🇵",
  American: "🇺🇸",
  Danish: "🇩🇰",
  Chinese: "🇨🇳",
  "New Zealander": "🇳🇿",
  Argentine: "🇦🇷",
  Argentinian: "🇦🇷",
  Brazilian: "🇧🇷",
  Austrian: "🇦🇹",
  Belgian: "🇧🇪",
  Swiss: "🇨🇭",
  Swedish: "🇸🇪",
  Polish: "🇵🇱",
  Russian: "🇷🇺",
  Estonian: "🇪🇪",
  Irish: "🇮🇪",
  "South African": "🇿🇦",
};

export const flag = (nationality?: string) => NATION_FLAG[nationality ?? ""] ?? "🏁";
